name: Publish dev release
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and attach .deb and .whl package
    if: github.repository == 'vision-web3-foundation/validatornode'
    uses: ./.github/workflows/build.yml
    secrets: 'inherit'

  publish-docker:
    uses: ./.github/workflows/publish-docker.yaml
    if: github.repository == 'vision-web3-foundation/validatornode'
    needs: build
    secrets: 'inherit'
    with:
      tag: development
      environment: main
      cache_enabled: true

  test:
    needs: publish-docker
    uses: vision-web3-foundation/e2e-testing/.github/workflows/ci.yaml@main
