name: Sonar

on:
  workflow_run:
    workflows: [CI]
    types: [completed]

jobs:
  shared:
    if: github.repository == 'vision-web3-foundation/validatornode'
    uses: vision-web3-foundation/ci-workflows/.github/workflows/sonar.yml@v1
    secrets: inherit
